### ISSUE TITLE
Integration broken after update to HA Core 2024.7.0

### ISSUE THREAD

**Issue by xenoOdem** [z8i/ha_custom_klimaloggpro#7]
Thanks a lot for your Klimalogg pro integration! I'm only into Home Assistant for 1 month now and it worked instantly when I installed it.
BUT: Yesterday evening **I updated to HA core 2024.7.0 and unfortunately no values were available any more.**
I decided to start a debug protocol and there were errors visible. Especially I understood the following 2 warnings:

2024-07-04 21:37:36.228 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", True)])`; **This function will be removed in 2025.7** at custom_components/hacs/base.py, line 1162: self.hass.http.register_static_path(, **please create a bug report at https://github.com/hacs/integration/issues**
2024-07-04 21:37:36.296 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/lib/usb-1.0', 'rb') **inside the event loop by custom integration 'klimaloggpro'** at custom_components/klimaloggpro/__init__.py, line 33: hass.data[DOMAIN]["kldr"] = kloggpro.klimalogg.KlimaLoggDriver() # creates an instance of the klimalogg-device (offender: /usr/local/lib/python3.12/ctypes/util.py, line 276: with open(filepath, 'rb') as fh:), please report it to the author of the 'klimaloggpro' custom integration

**I did not report to hacs/integration/issues up to now** - maybe this can be resolved by you. Otherwise please report it from your side.

For the moment I could get it to work again by downgrading via installing my backup of the previous version 2024.6.4

**The debug protocol is attached**. Hope this is what you need to adjust the integration.
[home-assistant_klimaloggpro_2024-07-04T21-04-49.274Z.log](https://github.com/user-attachments/files/16104883/home-assistant_klimaloggpro_2024-07-04T21-04-49.274Z.log)

**Comment by TiberiusRegenschein** [comment]
I was happily using the integration since about 8 month now. It worked flawlessly. Now with version 2024.7.0 I can connect to the USB dongle anymore.

I get the error message:
Logger: homeassistant.config_entries
Quelle: config_entries.py:586
Erstmals aufgetreten: 19:46:23 (2 Vorkommnisse)
Zuletzt protokolliert: 20:24:46

Error setting up entry KlimaloggPro for klimaloggpro
Traceback (most recent call last):
  File "/var/www/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xyz.app/homeassistant/custom_components/klimaloggpro/__init__.py", line 33, in async_setup_entry
    hass.data[DOMAIN]["kldr"] = kloggpro.klimalogg.KlimaLoggDriver() # creates an instance of the klimalogg-device
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/homeassistant/lib/python3.12/site-packages/kloggpro/klimalogg.py", line 1627, in __init__
    self.startUp()
  File "/var/www/homeassistant/lib/python3.12/site-packages/kloggpro/klimalogg.py", line 1835, in startUp
    self._service.setup(self.frequency, self.comm_interval,
  File "/var/www/homeassistant/lib/python3.12/site-packages/kloggpro/klimalogg.py", line 910, in setup
    self.hid.open(vendor_id, product_id, serial)
  File "/var/www/homeassistant/lib/python3.12/site-packages/kloggpro/klimalogg.py", line 2333, in open
    self.devh = self._open_device(device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/homeassistant/lib/python3.12/site-packages/kloggpro/klimalogg.py", line 2410, in _open_device
    time.sleep(usb_wait)
  File "/var/www/homeassistant/lib/python3.12/site-packages/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/var/www/homeassistant/lib/python3.12/site-packages/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.05,) inside the event loop by custom integration 'klimaloggpro' at custom_components/klimaloggpro/__init__.py, line 33: hass.data[DOMAIN]["kldr"] = kloggpro.klimalogg.KlimaLoggDriver() # creates an instance of the klimalogg-device. (offender: /var/www/homeassistant/lib/python3.12/site-packages/kloggpro/klimalogg.py, line 2410: time.sleep(usb_wait)), please report it to the author of the 'klimaloggpro' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
Assuming this has the same root cause, I added it to this threat. Happy to start a new one in case the root cause differs

**Comment by z8i** [comment]
tried some asyncs with the new version, but still broken...

**Comment by patentuck** [comment]
I have also been using the klimalogg integration for a long time without any significant problem and I am very grateful for it. Since it has not been working since the July version of Home Assistant, I had to downgrade to the last working version, 2024.6.4 of Home Assistant. I really hope that the klimalogg integration gets fixed and thank you in advance for your work.

**Comment by z8i** [comment]
now it should be working again. please try and let me know!
https://github.com/z8i/ha_custom_klimaloggpro/commit/0f290386cc26e21d2c966b1f65da21f710ae3982

**Comment by patentuck** [comment]
Dear Martin,works fine again! Thanks a lot for your work,Ludger
